# Generated by Django 3.1.6 on 2022-09-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='two_factor_authentication_validated',
            field=models.BooleanField(default=False),
        ),
    ]
