# Generated by Django 3.1.6 on 2022-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_two_factor_authentication_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='two_factor_authentication',
            new_name='double_authentication',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='code_tfa',
            new_name='double_authentication_code',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='two_factor_authentication_validated',
            new_name='double_authentication_validated',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='state',
            field=models.CharField(default='done', max_length=100),
        ),
    ]
