# Generated by Django 3.1.6 on 2022-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220909_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='datetime_transfer',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
