# Generated by Django 3.1.6 on 2022-09-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220909_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='transactions',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
