# Generated by Django 3.1.6 on 2022-09-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220909_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='datetime_transfer',
            field=models.DateTimeField(),
        ),
    ]
